kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "openshift-build-pipeline-$VERSION" 
spec:
  source: 
    git:
      uri: "https://github.com/LiXianTee/helloworld-openshift.git"
  strategy: 
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: DockerImage
      name: $APP_IMAGE
    pushSecret:
      name: nexus-secret
